apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-argo-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/Harshwardhanjadhav0/GitOps-argocd-automation-eks-.git
    path: myHelmcharts/mychart
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
