apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-argo
  name: webapp-argo-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp-argo
  type: LoadBalancer
status:
  loadBalancer: {}
